### PR TITLE
Setup layout and navbar

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
image

## Summary by CodeRabbit

- **New Features**
  - Introduced a development container configuration for improved setup in VS Code.
  - Added new GitHub Actions job for running Playwright tests.
  - Implemented new navigation bar and dropdown components for enhanced user interaction.
  - Added a responsive mobile menu to the navigation bar.
  - New layout component `AppLayout` introduced for consistent application structuring.
  - Added new scripts in `package.json` for specific development and testing workflows.

- **Enhancements**
  - Updated Playwright tests to include more comprehensive test scenarios.
  
- **Bug Fixes**
  - Updated dependency version to ensure compatibility and stability.

- **Documentation**
  - Updated `.gitignore` to exclude `yarn.lock` from version control to avoid conflicts.

### CODE REVIEW

**Comment by Megha-Dev-19** [comment]
I am having trouble generating package.lock on my local, if someone can push it, it would be great.

**Comment by petersalomonsen** [comment]
please merge [this branch](https://github.com/NEAR-DevHub/near-prpsls-bos/pull/4) to your PR @Megha-Dev-19  and then it should be ok.

**Comment by Megha-Dev-19** [comment]
@petersalomonsen should we merge it?

**Comment by petersalomonsen** [comment]
yes @Megha-Dev-19 . Go ahead!

**Pull request merged**
