### PR TITLE
Rfp create

### PR DESCRIPTION
**Pull request by petersalomonsen**
Tests shows opening the RFP page, asserts that an RFP item exists, and try searching for an non-existing RFP and asserts no results.

https://github.com/NEAR-DevHub/near-prpsls-bos/assets/9760441/57b99b6d-334f-4ca3-beee-ac2066460d44

Also checking if admin is allowed to create rfp, and fill the form

https://github.com/NEAR-DevHub/near-prpsls-bos/assets/9760441/b9f02458-73c2-41b9-aa84-3b839a526e6a

### CODE REVIEW

**Comment by petersalomonsen** [comment]
@Megha-Dev-19 What is supposed to happen here? It is just spinning for me in my test

https://github.com/NEAR-DevHub/near-prpsls-bos/assets/9760441/bbbe4f63-2544-4be4-95b9-0280e49fbe47

**Comment by Megha-Dev-19** [comment]
hey @petersalomonsen, I believe Vadim deployed a newer version of contract and indexer, because of which this changed, I will update it and let you know.

**Comment by petersalomonsen** [comment]
@Megha-Dev-19 see the updated tests now, also including filling the RFP form. Do you see more test cases that could be added? What about "Don't ask again", is that handled?

**Review by Megha-Dev-19 — APPROVED** [review]
Looks great @petersalomonsen

**Pull request merged**
